# Planar Bridge example config file

# Download reprints (significantly increases amount of duplicate cards).
pull_reprints = false

# Download a few scans of various cardbacks.
pull_cardbacks = false

# Exclude sets that should not be downloaded.
# These sets listed below are purely comprised of reprints.
exempt_sets = [
    "MB1",
    "PDRC",
    "PLIST",
    "PURL",
    "UPLIST",
]

# (CURRENTY UNIMPLEMENTED!) List of sets that should always be parsed.
continuous_sets = ["SLD", "SLU", "SLX"]

# Exclude certain promotional cards included in regular sets.
# Full list of values can be found here:
# https://mtgjson.com/data-models/card-set/#promotypes
exempt_promos = [
    "datestamped",
    "draftweekend",
    "gameday",
    "intropack",
    "jpwalker",
    "mediainsert",
    "planeswalkerstamped",
    "playerrewards",
    "premiereshop",
    "prerelease",
    "promopack",
    "release",
    "setpromo",
    "stamped",
    "themepack",
    "thick",
    "tourney",
    "wizardsplaynetwork",
]

# Exclude specific types of sets from being downloaded.
# Full list of values can be found here:
# https://mtgjson.com/data-models/set/#type
exempt_types = [
    "alchemy",
    "funny",
    "memorabilia",
    "token",
]

# List of sets that should be re-included if under an excluded type.
pardoned_sets = [
    "2X2",
    "CLB",
    "DBL",
]

# Preferred language of downloaded cards.
# (Keep in mind that many sets are only printed in English!)
#card_lang = "en"
