xmt_types = [
    'funny',
    'memorabilia'
]

xmt_sets = [
    'MB1',
    'PDRC',
    'PLIST',
    'PURL'
]

xmt_promos = [
    'datestamped',
    'draftweekend',
    'gameday',
    'intropack',
    'jpwalker',
    'mediainsert',
    'planeswalkerstamped',
    'playerrewards',
    'premiereshop',
    'prerelease',
    'promopack',
    'release',
    'setpromo',
    'stamped',
    'themepack',
    'tourney',
    'wizardsplaynetwork'
]
